FindJobSolution.AdminApp/Controllers/Componets/PagerViewComponent.cs
using FindJobSolution.ViewModels.Common;
using Microsoft.AspNetCore.Mvc;

namespace FindJobSolution.AdminApp.Controllers.Componets
{
    public class PagerViewComponent : ViewComponent
    {
        public Task<IViewComponentResult> InvokeAsync(PagedResultBase request)
        {
            return Task.FromResult((IViewComponentResult)View("Defaut", request));
        }
    }
}

FindJobSolution.AdminApp/Controllers/ReportController.cs
using FindJobSolution.APItotwoweb.API;
using FindJobSolution.ViewModels.Catalog.Report;
using FindJobSolution.ViewModels.Catalog.Skills;
using Microsoft.AspNetCore.Mvc;

namespace FindJobSolution.AdminApp.Controllers
{
    public class ReportController : Controller
    {
        private readonly IReportAPI _reportAPI;
        private readonly IConfiguration _configuration;

        public ReportController(IReportAPI reportAPI, IConfiguration configuration)
        {
            _reportAPI = reportAPI;
            _configuration = configuration;
        }

        public async Task<IActionResult> Index(string keyWord, int pageIndex = 1, int pageSize = 10)
        {
            var request = new GetReportPagingRequest()
            {
                keyword = keyWord,
                PageIndex = pageIndex,
                PageSize = pageSize
            };
            var data = await _reportAPI.GetAllPaging(request);
            return View(data);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Delete(ReportDeleteVM request)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            var result = await _reportAPI.Delete(request.id);
            if (result)
            {
                return RedirectToAction("index");
            }
            return View(request);
        }
    }
}

FindJobSolution.AdminApp/Controllers/UserController.cs
using FindJobSolution.APItotwoweb.API;
using FindJobSolution.ViewModels.Common;
using FindJobSolution.ViewModels.System.Role;
using FindJobSolution.ViewModels.System.User;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FindJobSolution.AdminApp.Controllers
{
    [Authorize]
    public class UserController : BaseController
    {
        private readonly IUserAPI _userAPI;
        private readonly IConfiguration _configuration;
        private readonly IRoleApi _roleApi;

        public UserController(IUserAPI userAPI, IConfiguration configuration, IRoleApi roleApi)
        {
            _userAPI = userAPI;
            _configuration = configuration;
            _roleApi = roleApi;
        }

        public async Task<IActionResult> Index(string keyWord, int pageIndex = 1, int pageSize = 5)
        {
            var request = new GetUserPagingRequest()
            {
                keyword = keyWord,
                PageIndex = pageIndex,
                PageSize = pageSize
            };
            var data = await _userAPI.GetUsersPaging(request);
            return View(data);
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            var result = await _userAPI.GetById(id);
            return View(result);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(UserRegisterRequest request)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            var result = await _userAPI.Register(request);
            if (result)
            {
                TempData["result"] = "Create user successfully";
                return RedirectToAction("Index");
            }
            return View(request);
        }

        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            HttpContext.Session.Remove("Token");
            return RedirectToAction("index", "Login");
        }

        [HttpGet]
        public IActionResult Delete(Guid id)
        {
            return View(new UserDeleteRequest()
            {
                Id = id
            });
        }

        [HttpPost]
        public async Task<IActionResult> Delete(UserDeleteRequest request)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            var result = await _userAPI.Delete(request.Id);
            if (result)
            {
                TempData["result"] = "Delete user successfully";
                return RedirectToAction("Index");
            }
            return View(request);
        }

        [HttpGet]
        public async Task<IActionResult> RoleAssign(Guid id)
        {
            var roleAssignRequest = await GetRoleAssignRequest(id);
            return View(roleAssignRequest); //
        }

        [HttpPost]
        public async Task<IActionResult> RoleAssign(RoleAssignRequest request)
        {
            if (!ModelState.IsValid)
                return View();

            var result = await _userAPI.RoleAssign(request.Id, request);

            if (result)
            {
                TempData["result"] = "Cập nhật quyền thành công";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", result.ToString());
            var roleAssignRequest = await GetRoleAssignRequest(request.Id);

            return View(roleAssignRequest); //
        }

        private async Task<RoleAssignRequest> GetRoleAssignRequest(Guid id)
        {
            var userObj = await _userAPI.GetById(id);
            var roleObj = await _roleApi.GetAll();
            var roleAssignRequest = new RoleAssignRequest();
            foreach (var role in roleObj.ResultObj)
            {
                roleAssignRequest.Roles.Add(new SelectItem()
                {
                    Id = role.Id.ToString(),
                    Name = role.Name,
                    Selected = userObj.Roles.Contains(role.Name)
                });
            }
            return roleAssignRequest;
        }
    }
}

FindJobSolution.AdminApp/Views/Report/Delete.cshtml
@model FindJobSolution.ViewModels.Catalog.Report.ReportDeleteVM

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container-fluid px-4">
    <h1 class="mt-4">Xóa phản hồi từ người dùng</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="/home/index">Trang chủ</a></li>
        <li class="breadcrumb-item active">Bạn có chắc muốn xóa phản hồi này?</li>
    </ol>

    <div class="card mb-4">
        @*<div class="card-header">
        <a class="btn btn-success" asp-action="Create" asp-controller="User">Tạo người dùng mới</a>
        </div>*@
        <div class="card-body">
            <div class="table-responsive">

                <form asp-action="Delete">
                    <input type="submit" value="Xóa" class="btn btn-danger" /> |
                    <a class="btn btn-success" asp-action="index" asp-controller="jobseeker">Trở lại danh sách</a>
                </form>
            </div>
        </div>
    </div>
</div>

FindJobSolution.AdminApp/Views/Report/Index.cshtml
@using FindJobSolution.ViewModels.Common
@model PagedResult<FindJobSolution.ViewModels.Catalog.Report.ReportVM>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container-fluid px-4">
    <h1 class="mt-4">Danh sách phản hồi từ người dùng</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="/home/index">Trang chủ</a></li>
        <li class="breadcrumb-item active">Danh sách phản hồi từ người dùng</li>
    </ol>

    <div class="card mb-4">
        @*<div class="card-header">
        <a class="btn btn-success" asp-action="Create" asp-controller="User">Tạo người dùng mới</a>
        </div>*@
        <div class="card-body">
            <div class="table-responsive">
                @*<p>
                <a asp-action="Create">Tạo nhà tuyển dụng mới</a>
                </p>*@
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>
                                Tên người dùng
                            </th>
                            <th>
                                Nội dung
                            </th>
                            <th>
                                Thời gian
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Items)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Content)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Date)
                                </td>
                                <td>
                                    @Html.ActionLink("Xóa", "Delete", new {  id=item.id  }, new { @class = "btn btn-danger" })
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>


            </div>
            @await Component.InvokeAsync("Pager", Model)
        </div>
    </div>
</div>